apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ovsnets.networking.ik8s.ir
spec:
  group: networking.ik8s.ir
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bridge:
                  type: string
                status:
                  type: string
      additionalPrinterColumns:
        - name: bridge
          type: string
          jsonPath: .spec.bridge
        - name: status
          type: string
          jsonPath: .spec.status
  scope: Namespaced
  names:
    kind: OVSNet
    plural: ovsnets
    singular: ovsnet
    shortNames:
    - ovsnet