apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beaver
  name: ik8s-beaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ik8s-beaver
  template:
    metadata:
      labels:
        app: ik8s-beaver
    spec:
      containers:
      - image: dr.ik8s.ir/beaver
        imagePullPolicy: Always
        name: ik8s-beaver
        env:
        - name: ENV
          value: production
        - name: NAMESPACE
          value: ik8s-system
        - name: BEAVERAGENTPODNAME
          value: ik8s-beaveragent
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
